config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "/cards", to: "cards#index"
  # get "/new", to: "cards#new"
  # get "/cards/new", to: "cards#new"
  resources :cards

  get "/", to: "cards#index"
  # root "cards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
    # render html: "<h1>hello 123</h1>".html_safe
  end

  def new
    @card = Card.new
  end

  def edit
    @card = Card.find(params["id"])
  end

  def update
    @card = Card.find(params["id"])

    clean_params = params.require("card").permit(:title, :content)

    if @card.update(clean_params)
      redirect_to "/"
    else
      render :edit
    end
  end

  def destroy
    @card = Card.find(params["id"])
    @card.destroy
    redirect_to "/"
  end

  def create
    # clean_params = params["card"].permit(:title, :content)
    clean_params = params.require("card").permit(:title, :content)

    # 寫入資料
    @card = Card.new(clean_params)
    # @card = Card.new(title: "ccc", content: "ddd")

    if @card.save
      redirect_to "/"
    else
      render :new # borrow new.index.erb to render
      # redirect_to "/cards/new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<h1>編輯卡片</h1>
<% if @card.errors.any? %>
  <ul>
    <% @card.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for(@card) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <%= f.submit %>
<% end %>

app/views/cards/index.html.erb
<h1>卡片列表</h1>
<%# <a href="/cards/new">新增卡片</a> %>
<%# View helper %>
<%# link_to  "新增卡片", "cards/new" %>
<%= link_to  "新增卡片",  new_card_path %>
<hr>
<% @cards.each do |card| %>
  <div class='card'>
    <header class='card-title'>
      <%= card.title %>
      <%= link_to '編輯', edit_card_path(card.id) %>
      <%= link_to '刪除', card_path(card), method: 'delete',
      data:{confirm:'確定刪除'}%>
    </header>
    <div class='card-body'>
      <p><%= card.content %></p>
    </div>
  </div>
<% end %>

app/views/cards/new.html.erb
<h1>新增卡片</h1>
<% if @card.errors.any? %>
  <ul>
    <% @card.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for(@card) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <%= f.submit %>
<% end %>
<%# 
<form action="/cards" method="post">
  Title:<input type="text" />
  <button type="submit">新增</button>
</form> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PT1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>